version: '3.2'

services:
  reverse:
    container_name: reverse-proxy
    image: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./config:/etc/nginx
      - ./certs:/etc/ssl/private
    restart: always